### ISSUE TITLE
Could you please help There is some error when i try to makemigrations

### ISSUE THREAD

**Issue by mubashar64** [zinmyoswe/Django-Ecommerce#3]
First of i am very thankful to you for your project it will helpful for learning and sharpen skill.  I am much interested to lean more from you do you have any youtube channel? 

I clone and setup in my windows system directly  after installing the packages i try to makemigrations. but there is some error coming. I really could not understand. Can you please help why the below error coming. Did i miss something?
D:\django\Django-Ecommerce-master>python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Mubashar\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\Mubashar\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Mubashar\Anaconda3\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Mubashar\Anaconda3\lib\site-packages\django\core\management\base.py", line 366, in execute
    self.check()
  File "C:\Users\Mubashar\Anaconda3\lib\site-packages\django\core\management\base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\Mubashar\Anaconda3\lib\site-packages\django\core\management\base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\Mubashar\Anaconda3\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\Mubashar\Anaconda3\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\Mubashar\Anaconda3\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\Mubashar\Anaconda3\lib\site-packages\django\urls\resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "C:\Users\Mubashar\Anaconda3\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Mubashar\Anaconda3\lib\site-packages\django\urls\resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\Mubashar\Anaconda3\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Mubashar\Anaconda3\lib\site-packages\django\urls\resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\Mubashar\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\django\Django-Ecommerce-master\demo\urls.py", line 9, in <module>
    path('', include('core.urls', namespace='core'))
  File "C:\Users\Mubashar\Anaconda3\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\Mubashar\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\django\Django-Ecommerce-master\core\urls.py", line 2, in <module>
    from .views import (
  File "D:\django\Django-Ecommerce-master\core\views.py", line 13, in <module>
    from django.shortcuts import render_to_response
ImportError: cannot import name 'render_to_response' from 'django.shortcuts' (C:\Users\Mubashar\Anaconda3\lib\site-packages\django\shortcuts.py)

Looking forward your kind response. 
Cordially

**Comment by zinmyoswe** [comment]
Don't u try this error on stackoverflow? I recommend justdjango youtube channel. And Telsuko youtube channel is best for django developers. 😄😄

**Comment by mubashar64** [comment]
Thanks @zinmyoswe for your reply and recommended channels. :)

**Comment by andreaspapav** [comment]
the actual solution though? cause i am having the same issues
